version: "3"
services:
  cache:
    image: redis:7-alpine
    volumes:
      - ./cache/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - default

  directus:
    build:
      context: extensions
      dockerfile : Dockerfile.prod
    depends_on:
      - cache
    deploy:
      replicas: 3
    environment:
      # general
      - PUBLIC_URL=${DIRECTUS_PUBLIC_URL}
      # database
      - DB_CLIENT=pg
      - DB_CONNECTION_STRING
      # security
      - KEY=${DIRECTUS_KEY}
      - SECRET=${DIRECTUS_SECRET}
      - REFRESH_TOKEN_TTL=1d
      - REFRESH_TOKEN_COOKIE_SECURE=true
      - REFRESH_TOKEN_COOKIE_SAME_SITE=strict
      - REFRESH_TOKEN_COOKIE_NAME=geodashboard_refresh_token
      - PASSWORD_RESET_URL_ALLOW_LIST=${DIRECTUS_PASSWORD_RESET_URL_ALLOW_LIST}
      # cors
      - CORS_ENABLED=true
      - CORS_ORIGIN=true
      # redis
      - REDIS=redis://cache:6379
      # rate limiting
      - RATE_LIMITER_ENABLED=true
      - RATE_LIMITER_STORE=redis
      # cache
      - CACHE_ENABLED=true
      - CACHE_STORE=redis
      - CACHE_AUTO_PURGE=true
      - CACHE_SYSTEM_TTL=5m
      - CACHE_SKIP_ALLOWED=true
      # file storage
      - STORAGE_LOCATIONS=s3
      - STORAGE_S3_DRIVER=s3
      - STORAGE_S3_KEY
      - STORAGE_S3_SECRET
      - STORAGE_S3_BUCKET
      - STORAGE_S3_ENDPOINT
      - STORAGE_S3_REGION
      - STORAGE_S3_ROOT
      - STORAGE_S3_FORCE_PATH_STYLE
      # telemetry
      - TELEMETRY=false
      # email
      # - EMAIL_TRANSPORT=ses
      # - EMAIL_FROM
      # - EMAIL_SES_CREDENTIALS__ACCESS_KEY_ID=${STORAGE_S3_KEY}
      # - EMAIL_SES_CREDENTIALS__SECRET_ACCESS_KEY=${STORAGE_S3_SECRET}
      # - EMAIL_SES_REGION=${STORAGE_S3_REGION}
      # auths
      # - SECUREWATCH_MAXAR_USERNAME
      # - SECUREWATCH_MAXAR_PASSWORD
      # PM2
      - PM2_INSTANCES=2
      - PM2_AUTO_RESTART=true
      # Sync
      - SYNCHRONIZATION_STORE=redis
      # user
      - ADMIN_TOKEN
    restart: unless-stopped
    networks:
      - default
      - geodashboard_data

  geoprocessing:
    build:
      context: manager/python
    environment:
      - TZ=Asia/Jakarta
      - DB_CONNECTION_STRING
      - STORAGE_S3_KEY
      - STORAGE_S3_SECRET
      - STORAGE_S3_ENDPOINT
      - STORAGE_S3_BUCKET
      - STORAGE_S3_REGION
      - STORAGE_S3_ROOT
      - ADMIN_TOKEN
      - DIRECTUS_PUBLIC_URL
      - ORS_KEY
      - HERE_KEY
      - ROAD_API_URL
      - ROAD_API_KEY
    restart: unless-stopped
    networks:
      - default
      - geodashboard_data

  graphile:
    build:
      context: manager/javascript
    environment:
      - DB_CONNECTION_STRING
      - STORAGE_S3_KEY
      - STORAGE_S3_SECRET
      - STORAGE_S3_ENDPOINT
      - STORAGE_S3_BUCKET
      - STORAGE_S3_REGION
      - STORAGE_S3_ROOT
    restart: unless-stopped
    networks:
      - default
      - geodashboard_data

  web:
    build:
      context: web
      dockerfile : Dockerfile.prod
    depends_on:
      - directus
    restart: unless-stopped
    networks:
      - default

  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    depends_on:
      - directus
      - web
    volumes:
      - "./server/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped
    networks:
      - default

networks:
  geodashboard_data:
    name: geodashboard_data
    external : true