[tool.poetry]
authors = ["Miko <jherjati@gmail.com>"]
description = ""
name = "braga-py-worker"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
dramatiq = "^1.14.2"
dramatiq-pg = "^0.11.0"
laspy = {extras = ["laszip", "lazrs"], version = "^2.5.3"}
minio = "^7.1.17"
psycopg2-binary = "^2.9.8"
py3dtiles = {extras = ["las"], version = "^7.0.0"}
python = ">=3.10,<3.12"
python-dotenv = "^1.0.0"
pandas = "2.3.2"
openpyxl = "3.1.5"
shapely = "2.1.2"
collection = "0.1.6"
openrouteservice = "2.3.3"
protobuf = "6.31.1"
ortools = "9.14.6206"
geopandas = "1.1.1"
scikit-learn = "<1.4"
osmnx = "2.0.7"
flexpolyline = "0.1.0"

[tool.poetry.group.dev.dependencies]
gdal = "3.8.5"
watchdog = "^3.0.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
