version: "3"
services:
  postgis:
    build:
      context: postgis
    ports:
      - 5432:5432
    volumes:
      - ./postgis/data:/var/lib/postgresql/data
      - ./postgis/backup:/var/backups/postgresql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - geodashboard_data
    restart: unless-stopped
    shm_size: 2gb

  minio:
    build:
      context: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${STORAGE_S3_KEY}
      - MINIO_ROOT_PASSWORD=${STORAGE_S3_SECRET}
    networks:
      - geodashboard_data
      - default
    restart: unless-stopped

  minioclient:
    build:
      context: minioclient
    depends_on:
      - minio
    environment:
      - S3_ACCESS_KEY=${STORAGE_S3_KEY}
      - S3_SECRET_KEY=${STORAGE_S3_SECRET}
      - S3_BUCKET_NAME=${STORAGE_S3_BUCKET}
    restart: on-failure

networks:
  geodashboard_data:
    name: geodashboard_data
