name: EB deploy (Surge Dev)

on:
  push:
    branches: [surge-dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js for Directus
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm 8
        with:
          version: 8
          run_install: false

      - name: Install and build directus
        run: |
          pnpm install
          pnpm build
        working-directory: extensions

      - name: Install Node.js for Web
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: pnpm/action-setup@v2
        name: Install pnpm 9
        with:
          version: 9
          run_install: false

      - name: Install and build client
        run: |
          pnpm install
          pnpm build
        working-directory: web

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install EB CLI using pip
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Create Zip App Bundle
        run: |
          python3 create_eb_zip.py

      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy
