# Stage 1: Builder
FROM node:20-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git

COPY package*.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install

COPY . .

ENV NODE_ENV=production
RUN pnpm build

# Stage 2: Runner
FROM node:20-alpine AS runner

WORKDIR /src

COPY --from=builder /app/.output /src/.output

ENV NODE_ENV=production
CMD ["node", ".output/server/index.mjs"]